### ISSUE TITLE
Translations: Add data structure for linking, multiple translators/contributors?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#143]
rel: https://github.com/w3c/wai-video-standards-and-benefits/pull/53

We also might want to add the possibility to specify multiple translators/contributors in that phase.

**Comment by yatil** [comment]
@slhenry I plan to do the following:

```yaml
translators:
- name: Name 1
  link: https://example.com
  org: Org 1
  orglink: https://acme.example.com
- name: Name 2
  link: https://2.example.com
  org: Org 2
  orglink: https://acme2.example.com
```

The resulting HTML would be:

```html
<a href="https://example.com" rel="nofollow noopener" target="_blank">Name 1</a> 
(<a href="https://acme.example.com" rel="nofollow noopener" target="_blank">Org 1</a>), 
<a href="https://2.example.com" rel="nofollow noopener" target="_blank">Name 2</a> 
(<a href="https://acme2.example.com" rel="nofollow noopener" target="_blank">Org 2</a>)
```

Of course, if a field is empty (link, org), then the name would not be linked or the org would not be shown/linked. 

I plan to make the links open in new windows, which means also adding an icon that we do that. We could also keep the links open in the same window, which would be fine for me. What do you think?

**Comment by yatil** [comment]
I think this should also include “funded by” information, so maybe three sections like: 

```yaml
translators:
- name: Name 1
  link: https://example.com
  org: Org 1
  orglink: https://acme.example.com
- name: Name 2
  link: https://2.example.com
  org: Org 2
  orglink: https://acme2.example.com
contributors:
- name: Name 1
  link: https://example.com
  org: Org 1
  orglink: https://acme.example.com
- name: Name 2
  link: https://2.example.com
  org: Org 2
  orglink: https://acme2.example.com
funding:
- org: Org 1
  orglink: https://acme.example.com
- org: Org 2
  orglink: https://acme2.example.com
```
